export const actionTypes = {
  SET_LIST_FILM: " SET_LIST_FILM",
  SET_FILM_DETAIL: " SET_FILM_DETAIL",
  SET_ME: "SET_ME",
  DELETE_FILM: "DELETE_FILM",
  SET_CINEMA: " SET_CINEMA",
  SET_LIST_USER: " SET_LIST_USER",
  SET_MALOAINGUOIDUNG: " SET_MALOAINGUOIDUNG",
};
